# create_machine.yml

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Provision a set of instances
      ec2:
         key_name: my_key
         group: test
         instance_type: t2.micro
         image: "{{ ami_id }}"
         wait: true
         exact_count: 1
         count_tag:
            Name: teknoir_web
         instance_tags:
            Name: teknoir_web
      register: ec2

- name: Add all instance public IPs to host group
     add_host: hostname={{ item.public_ip }} groups=ec2hosts
     with_items: ec2.instances

- hosts: ec2hosts
  name: configuration play
  user: ec2-user
  gather_facts: true

  tasks:
     - name: Check NTP service
       service: name=ntpd state=started

